[project]
name = "demerzel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evaluate",
    "rouge_score",
   "loralib",
   "peft",
    "papermill",
    "tqdm",
   "trl",
    "pydantic",
    "numpy",
    "scikit-learn",
    "pyarrow",
    "setuptools",
   "accelerate",
   "weaviate-client",
   "vllm",
   "deprecated",
   "optimum",
]


# "evaluate<0.5",
#     "rouge_score",
#    "loralib",
#    "peft",
#     "papermill",
#     "torch>=2.0,<2.5",
#     "tqdm",
#    "trl",
#     "pydantic",
#     "numpy",
#     "scikit-learn<1.6",
#     "setuptools",
#     "numpy>=1.26,<2.0",
#     "pyarrow<15",
#    "accelerate",
#    "weaviate-client",
#    "vllm",
#    "deprecated",
#    "optimum",