[project]
name = "demerzel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evaluate",
    "rouge_score",
    "loralib",
    "peft",
    "papermill",
    "tqdm",
    "trl",
    "pydantic",
    "numpy",
    "scikit-learn",
    "pyarrow",
    "setuptools",
    "accelerate",
    "weaviate-client", #  "weaviate-client>=3.26.7,<4.0.0"
    "vllm",
    "deprecated",
    "optimum",
    "langchain-community",
    "sentence-transformers",
    # might need to comment datasets and downgrade to less than 3
    "dataset",
]
